# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './version.json'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Create Release On Monday
        run: |
          curl --location --request POST 'https://api.monday.com/v2/' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.MONDAY_TOKEN }}' \
          --data-raw '{"query":"mutation {\n  create_item(\n  board_id: 3285229350, \n  group_id: \"new_group\", \n  item_name: \"Vx.x.1\", \n  column_values: \"{ \\\"status\\\": { \\\"index\\\": 1 }, \\\"link\\\": { \\\"url\\\": \\\"www.github.com\\\", \\\"text\\\": \\\"See release details\\\" }, \\\"text\\\": \\\"-\\\" }\") {\n    id\n  }\n}","variables":{}}'
